
prompts_und_antworten=[
    {
        "original_prompt": "Few-Shot Prompting: **Umformulierte Problemstellung:**\n\n**Titel:** Vereinfachte Darstellung von GreenIT für eine breite Öffentlichkeit\n\n**Ziel:** Erklären Sie die Grundlagen und Vorteile von GreenIT in einer **20-minütigen Präsentation**, die speziell für **Laien ohne technischen Hintergrund** konzipiert ist, um das Thema zugänglich und verständlich zu machen.\n\n**Schwerpunkte:**\n1. **Einfache Definition:** Was ist GreenIT?\n2. **Umweltauswirkungen:** Warum ist GreenIT wichtig für die Umwelt?\n3. **Praktische Beispiele:** Alltagsbeispiele, die die Anwendung von GreenIT veranschaulichen\n4. **Zukunftsperspektiven:** Kurze Einblicke in die Zukunft von GreenIT und seine potenziellen Auswirkungen",
        "technique": "Few-Shot Prompting",
        "generated_prompt": "Wie würde eine effective 20-minütige Präsentation für Laien ohne technischen Hintergrund über GreenIT aussehen, die dessen Grundlagen, Umweltauswirkungen, praktische Beispiele und Zukunftsperspektiven einfach verständlich macht?",
        "answer": "Präsentationstitel: **Grün durch Clicks - Einfach erklärt: GreenIT für Alle**\n\n**Minute 1-3: Einfache Definition & Einleitung**\n* Visuals: Animationsvideo mit grün werdender Stadt/ Natur\n* Erklärung: 'GreenIT bedeutet \"grüne\" Informationenstechnologie. Es geht darum, unsere Computer, Server und ganze digitale Welt umweltfreundlicher zu gestalten.'\n* Interaktion: Kurze Umfrage via Applaus oder Abstimmungskarten: 'Wer von Ihnen schon einmal von GreenIT gehört hat?'\n\n**Minute 4-8: Umweltauswirkungen**\n* Visuals: Vergleichsbilder (CO2-Ausstoß von Autos vs. Serverfarmen, E-Waste-Berge)\n* Erklärung: 'Unser Internetverbrauch verursacht mehr CO2 als der globale Luftverkehr. GreenIT zielt darauf ab, diesen Fußabdruck zu minimieren.'\n* Statistik per Bild: 'Ein Server verbraucht so viel Strom wie ein durchschnittliches Haushaltsgerät. Stellen Sie sich Tausende davon vor...'\n\n**Minute 9-14: Praktische Beispiele**\n* **Beispiel 1 - energiesparende Hardware:** Bild eines energieeffizienten Computers neben einem herkömmlichen\n* **Beispiel 2 - Cloud Computing:** Animationsvideo, das den geringeren Bedarf an persönlichen Servern veranschaulicht\n* **Beispiel 3 -digitale Lösungen für weniger Plastik:** Bild eines E-Book-Readers neben einem Regal mit Büchern\n\n**Minute 15-18: Zukunftsperspektiven**\n* Visuals: Concept-Art von nachhaltigen, futuristischen Städten mit integrierter GreenIT-Infrastruktur\n* Erklärung: 'In Zukunft wird GreenIT nicht nur die Umwelt schützen, sondern auch neue, innovative Wege für unsere Arbeit und Freizeit eröffnen.'\n* Zitate von GreenIT-Pionieren auf dem Bildschirm, die die Visionen für ein grüneres Morgen teilen\n\n**Minute 19-20: Abschluss & Call to Action**\n* Zusammenfassung als Infografik auf der Präsentationsfolie\n* Aufruf: 'Machen Sie mit! Jeder Klick, jede Wahl für GreenIT zählt - für unsere Zukunft.'\n* Endscreen mit Links zu GreenIT-Ressourcen für weitere Informationen"
    },
    {
        "original_prompt": "Role / Objective / Details / Examples / Sense Check: **Umformulierte Problemstellung:**\n\n**Titel:** Vereinfachte Darstellung von GreenIT für eine breite Öffentlichkeit\n\n**Ziel:** Erklären Sie die Grundlagen und Vorteile von GreenIT in einer **20-minütigen Präsentation**, die speziell für **Laien ohne technischen Hintergrund** konzipiert ist, um das Thema zugänglich und verständlich zu machen.\n\n**Schwerpunkte:**\n1. **Einfache Definition:** Was ist GreenIT?\n2. **Umweltauswirkungen:** Warum ist GreenIT wichtig für die Umwelt?\n3. **Praktische Beispiele:** Alltagsbeispiele, die die Anwendung von GreenIT veranschaulichen\n4. **Zukunftsperspektiven:** Kurze Einblicke in die Zukunft von GreenIT und seine potenziellen Auswirkungen",
        "technique": "Role / Objective / Details / Examples / Sense Check",
        "generated_prompt": "How might a 20-minute presentation effectively explain GreenIT to a non-technical audience, highlighting its simplicity, environmental impact, practical examples, and future perspectives?",
        "answer": "Here is a potential outline for the presentation, broken down into the requested 20-minute timeframe (approximate durations included):\n\n**Minutes 1-3: Einfache Definition - Was ist GreenIT?**\n*   Start with a relatable analogy: Compare GreenIT to energy-efficient home appliances, highlighting how both reduce environmental footprint.\n*   **Slide 1: Title Slide with \"GreenIT Explained Simply\"**\n*   **Slide 2: Analogy Explanation**\n*   **Definition:** 'GreenIT refers to the practice of using Information Technology (IT) in a way that minimizes environmental impact, just like how you use energy-saving light bulbs at home.'\n\n**Minutes 4-8: Umweltauswirkungen - Warum ist GreenIT wichtig für die Umwelt?**\n*   Visual aids: Show drastic Before-After images of environmental degradation vs. conservation.\n*   **Key Stats:**\n    *   E-waste contribution to landfills\n    *   Carbon footprint reduction through GreenIT practices\n*   **Slide 3: Environmental Impact Images**\n*   **Slide 4: Statistics and Graphs**\n\n**Minutes 9-14: Praktische Beispiele - Alltagsbeispiele für GreenIT**\n*   **Example 1 (Minutes 9-10):**\n    *   **Slide 5: Cloud Computing Image**\n    *   Explanation: How cloud computing reduces the need for personal storage devices, thus lowering e-waste.\n*   **Example 2 (Minutes 11-12):**\n    *   **Slide 6: Remote Work Setup Image**\n    *   Explanation: Discuss how remote work, facilitated by GreenIT, reduces commuting and its associated emissions.\n*   **Example 3 (Minutes 13-14):**\n    *   **Slide 7: Eco-Friendly Gadgets Image**\n    *   Explanation: Highlight eco-friendly gadgets designed with recyclable materials or energy-harvesting technologies.\n\n**Minutes 15-18: Zukunftsperspektiven - Einblicke in die Zukunft von GreenIT**\n*   **Trend 1 (Minutes 15-16):**\n    *   **Slide 8: Quantum Computing Illustration**\n    *   Explanation: Briefly introduce how future technologies like quantum computing might further environmental goals.\n*   **Trend 2 (Minutes 17-18):**\n    *   **Slide 9: AI for Sustainability Image**\n    *   Explanation: Discuss the potential of AI in optimizing resource usage and predicting environmental outcomes.\n\n**Minutes 19-20: Zusammenfassung und Aufruf zur Aktion**\n*   Recap the key points in **Slide 10: Summary Slide**\n*   End with a **Call to Action** in **Slide 11: Join the GreenIT Movement**\n*   Encourage the audience to share one eco-friendly IT practice they plan to adopt post-presentation."
    }
]

for item in prompts_und_antworten:
    prompt = item['generated_prompt']
    antwort = item['answer']
    print(prompt)
    print(antwort)